---
- name: When conditionals
  hosts: localhost
  
  - name: Run 1 Conditional
    debug:
      var: C
    when: C is defined
	
  - name: Run Multiple Conditional to a single variable
    debug:
      var: C
    when: C is defined and C = "Multiple"

  - name: Show Var when conditional is undefined
    debug:
      var: C
    when: C is not defined	